spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_tests
    username: root
    password: S1V1sP4c3mP4r4B3llum
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---
environment: test
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
    driver-class-name:  org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enable: true
